import React,{useEffect,useState}from'react';
import{createRoot}from'react-dom/client';
import{ArrowLeft,BookOpen,Camera,Check,ChevronRight,Heart,Home,ImagePlus,Info,LogOut,MapPin,MessageSquare,Palette,RefreshCw,Search,Settings,ShieldCheck,ShoppingBag,Sparkles,Star,Trash2,UserRound,WandSparkles}from'lucide-react';
import'./style.css';
import{backendReady,loadJourney,saveJourney,supabase}from'./lib/supabase';

const modules=[
 {id:'analysis',title:'Analisar minhas linhas',desc:'Fotos guiadas + análise de linhas corporais',icon:Camera},
 {id:'identity',title:'Descobrir meu estilo',desc:'Preferências, rotina e objetivos',icon:Sparkles},
 {id:'guide',title:'Meu guia pessoal',desc:'Recomendações feitas para você',icon:BookOpen},
 {id:'looks',title:'Montar um look',desc:'Combinações para cada ocasião',icon:ShoppingBag},
 {id:'colors',title:'Cores & beleza',desc:'Contraste, paleta e cabelo',icon:Palette},
 {id:'pros',title:'Encontrar profissional',desc:'Consultoras e serviços especializados',icon:UserRound}
];
const quiz=[
 {title:'Como você quer se sentir ao se vestir?',options:['Elegante e segura','Criativa e marcante','Leve e natural','Moderna e poderosa']},
 {title:'Qual é sua maior dificuldade hoje?',options:['Combinar o que já tenho','Comprar sem me arrepender','Entender o que me valoriza','Vestir minha nova fase']},
 {title:'Onde você mais precisa de ajuda?',options:['Trabalho','Dia a dia','Eventos','Em tudo um pouco']}
];
const styleProfiles={
 'Elegante e segura':{name:'Elegante essencial',summary:'Refinamento, segurança e linhas limpas formam a base do seu estilo.',silhouette:'Estrutura moderada, cintura sutil e caimento contínuo.',materials:'Alfaiataria leve, crepe, tricot fino e superfícies polidas.',details:'Poucos pontos de destaque, acessórios médios e acabamento preciso.',keywords:['refinada','segura','atemporal']},
 'Criativa e marcante':{name:'Criativa expressiva',summary:'Cor, contraste e detalhes autorais ajudam sua imagem a contar uma história.',silhouette:'Volumes estratégicos, sobreposições e proporções inesperadas.',materials:'Texturas aparentes, misturas de tecidos e acabamentos artesanais.',details:'Acessórios protagonistas, estampas gráficas e cor em pontos focais.',keywords:['autoral','marcante','inventiva']},
 'Leve e natural':{name:'Natural refinada',summary:'Conforto, movimento e simplicidade bem cuidada conduzem suas escolhas.',silhouette:'Formas descomplicadas, linhas soltas e estrutura suave.',materials:'Linho, algodão, malhas macias e texturas naturais.',details:'Acabamento fosco, formas orgânicas e acessórios funcionais.',keywords:['leve','acolhedora','autêntica']},
 'Moderna e poderosa':{name:'Moderna impactante',summary:'Geometria, presença e contraste traduzem uma imagem contemporânea.',silhouette:'Linhas retas, ombros definidos e proporções arquitetônicas.',materials:'Couro, sarja estruturada, alfaiataria e superfícies lisas.',details:'Metais, recortes geométricos e poucos elementos de alto impacto.',keywords:['forte','atual','estratégica']}
};
const getStyleProfile=profile=>styleProfiles[profile.answers?.[0]]||styleProfiles['Elegante e segura'];
const looks=[
 {occasion:'Trabalho',name:'Elegância sem esforço',pieces:['Blazer estruturado','Regata acetinada','Calça reta','Mocassim'],tone:'rose'},
 {occasion:'Fim de semana',name:'Natural sofisticado',pieces:['Camisa fluida','Jeans reto','Bolsa média','Sapatilha'],tone:'sand'},
 {occasion:'Evento',name:'Impacto delicado',pieces:['Vestido midi','Brinco orgânico','Sandália fina'],tone:'plum'}
];
const products=[
 {name:'Blazer alfaiataria',store:'Radar parceiro',price:'R$ 189',delivery:'Entrega em 3 dias',tone:'rose'},
 {name:'Calça reta premium',store:'Radar parceiro',price:'R$ 129',delivery:'Frete grátis',tone:'sand'},
 {name:'Bolsa estruturada',store:'Radar parceiro',price:'R$ 149',delivery:'Entrega amanhã',tone:'plum'}
];
const professionals=[
 {name:'Marina Lopes',role:'Consultora de imagem',place:'Brasília · Online',rating:'4,9',tag:'Estilo pessoal'},
 {name:'Clara Menezes',role:'Personal shopper',place:'Online',rating:'4,8',tag:'Compras inteligentes'},
 {name:'Nina Rocha',role:'Personal organizer',place:'Brasília',rating:'5,0',tag:'Closet e malas'}
];
const load=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};
const save=(key,value)=>{try{localStorage.setItem(key,JSON.stringify(value));return true}catch{return false}};
const photosReady=profile=>['frente','perfil','costas'].every(position=>profile.photos?.[position]);
const compressPhoto=file=>new Promise((resolve,reject)=>{if(!file.type.startsWith('image/'))return reject(new Error('Escolha um arquivo de imagem.'));if(file.size>15*1024*1024)return reject(new Error('A imagem deve ter no máximo 15 MB.'));const reader=new FileReader();reader.onerror=()=>reject(new Error('Não foi possível ler a imagem.'));reader.onload=()=>{const image=new Image();image.onerror=()=>reject(new Error('Imagem inválida ou corrompida.'));image.onload=()=>{const max=1200,scale=Math.min(1,max/Math.max(image.width,image.height));const canvas=document.createElement('canvas');canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL('image/jpeg',.76))};image.src=reader.result};reader.readAsDataURL(file)});

function Shell({screen,setScreen,children}){
 const page=modules.find(x=>x.id===screen)?.title;
 return <main className="app">
  {screen==='home'?<div className="top"><span className="logo">STYLIST <i>AI</i></span><button className="avatar" onClick={()=>setScreen('account')} aria-label="Abrir minha conta"><UserRound/></button></div>:<header><button className="iconButton" onClick={()=>setScreen('home')} aria-label="Voltar"><ArrowLeft/></button><b>{page||'Minha jornada'}</b><span className="headerMark">AI</span></header>}
  {children}
  {screen!=='home'&&<nav className="bottomNav"><button onClick={()=>setScreen('home')}><Home/><span>Início</span></button><button onClick={()=>setScreen('guide')}><BookOpen/><span>Guia</span></button><button onClick={()=>setScreen('looks')}><WandSparkles/><span>Looks</span></button><button onClick={()=>setScreen('pros')}><UserRound/><span>Experts</span></button></nav>}
 </main>
}

function App(){
 const[screen,setScreen]=useState('home');
 const[publicAuth,setPublicAuth]=useState(false);
 const[session,setSession]=useState(null);const[authLoading,setAuthLoading]=useState(backendReady);const[journeyLoaded,setJourneyLoaded]=useState(false);
 const[profile,setProfile]=useState(()=>backendReady?{answers:[],photos:{},favorites:[],completed:false}:load('stylist_profile',{answers:[],photos:{},favorites:[],completed:false}));
 const[storageError,setStorageError]=useState('');
 useEffect(()=>{if(!backendReady)return;supabase.auth.getSession().then(({data})=>{setSession(data.session);setAuthLoading(false)});const{data}=supabase.auth.onAuthStateChange((_event,next)=>{setSession(next);setAuthLoading(false);if(!next)setJourneyLoaded(false)});return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{if(!backendReady||!session)return;setJourneyLoaded(false);loadJourney(session.user.id).then(data=>{setProfile(data);setJourneyLoaded(true)}).catch(()=>setStorageError('Não foi possível carregar seus dados. Tente novamente.'))},[session?.user?.id]);
 useEffect(()=>{if(backendReady){if(!session||!journeyLoaded)return;const timer=setTimeout(()=>saveJourney(session.user.id,profile).catch(()=>setStorageError('Não foi possível salvar suas alterações.')),500);return()=>clearTimeout(timer)}if(!save('stylist_profile',profile))setStorageError('O navegador ficou sem espaço. Remova fotos antigas ou use imagens menores.')},[profile,session?.user?.id,journeyLoaded]);
 const eraseData=()=>{localStorage.removeItem('stylist_profile');setProfile({answers:[],photos:{},completed:false});setStorageError('');setScreen('home')};
 if(authLoading)return <main className="app centered"><span className="logo">STYLIST <i>AI</i></span><p>Carregando sua área...</p></main>;
 if(backendReady&&!session)return publicAuth?<Auth onBack={()=>setPublicAuth(false)}/>:<PublicLanding onStart={()=>setPublicAuth(true)}/>;
 return <Shell screen={screen} setScreen={setScreen}>
  {storageError&&<div className="errorBanner" role="alert">{storageError}</div>}
  {screen==='home'&&<HomePage setScreen={setScreen} profile={profile} eraseData={eraseData}/>}
  {screen==='analysis'&&<Analysis profile={profile} setProfile={setProfile} setScreen={setScreen}/>}
  {screen==='identity'&&<Identity profile={profile} setProfile={setProfile} setScreen={setScreen}/>}
  {screen==='result'&&<Result profile={profile} setScreen={setScreen}/>}
  {screen==='guide'&&<Guide profile={profile} setScreen={setScreen}/>}
  {screen==='looks'&&<Looks profile={profile}/>}
  {screen==='colors'&&<Colors/>}
  {screen==='pros'&&<Professionals/>}
  {screen==='radar'&&<Radar profile={profile}/>}
  {screen==='account'&&<Account session={session} profile={profile} setScreen={setScreen} setProfile={setProfile}/>} 
  {screen==='feedback'&&<Feedback session={session} setScreen={setScreen}/>} 
 </Shell>
}

function HomePage({setScreen,profile,eraseData}){
 return <>
  <section className="welcome"><span className="eyebrow">SEU ESTILO, COM INTENÇÃO</span><h1>Vista quem você quer ser.</h1><p>Descubra suas linhas, refine seu estilo e encontre as peças certas para você.</p><button className="primary" onClick={()=>setScreen(profile.completed?'result':'analysis')}>{profile.completed?'Ver meu perfil':'Fazer minha análise'} <ChevronRight/></button></section>
  {profile.completed&&<button className="progressCard" onClick={()=>setScreen('result')}><span><Check/> PERFIL INICIADO</span><b>Seu mapa de estilo está pronto</b><small>Veja sua primeira hipótese e continue refinando.</small><ChevronRight/></button>}
  <div className="sectionTitle"><h2>Seu espaço</h2><small>Uma jornada só sua</small></div>
  <section className="grid">{modules.map(({id,title,desc,icon:Icon})=><button className="feature" key={id} onClick={()=>setScreen(id==='identity'&&!photosReady(profile)?'analysis':id)}><Icon/><b>{title}</b><small>{id==='identity'&&!photosReady(profile)?'Comece pelas fotos guiadas':desc}</small><ChevronRight className="corner"/></button>)}</section>
  <button className="banner" onClick={()=>setScreen('radar')}><div><span className="pill">RADAR DE COMPRAS</span><h3>Seu look, encontrado.</h3><p>A IA sugere. O Radar encontra por preço, frete e entrega.</p></div><ShoppingBag/></button>
  <section className="dataPanel"><ShieldCheck/><div><b>Privacidade e dados</b><small>Fotos e respostas ficam somente neste navegador nesta demo.</small></div><button onClick={eraseData} disabled={!profile.answers?.length&&!Object.keys(profile.photos||{}).length}>Apagar meus dados</button></section>
 </>
}

function Analysis({profile,setProfile,setScreen}){
 const[step,setStep]=useState(0);const[consent,setConsent]=useState(Boolean(profile.consentAt));const[photoError,setPhotoError]=useState('');const positions=['frente','perfil','costas'];
 const setPhoto=async(position,file)=>{if(!file)return;setPhotoError('');try{const photo=await compressPhoto(file);setProfile(p=>({...p,photos:{...p.photos,[position]:photo}}))}catch(error){setPhotoError(error.message)}};
 const remove=position=>setProfile(p=>({...p,photos:{...p.photos,[position]:undefined}}));
 if(step===0)return <section className="card introCard"><span className="pill">ANÁLISE GUIADA</span><h1>Vamos conhecer suas linhas.</h1><p>Você adiciona três fotos e responde perguntas rápidas. A demo cria uma hipótese de estilo — não uma avaliação médica nem um julgamento do seu corpo.</p><div className="privacy"><Camera/><div><b>Suas fotos são suas</b><small>Nesta demo, elas ficam somente neste navegador, são comprimidas antes do armazenamento e podem ser apagadas na tela inicial.</small></div></div><label className="consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>Autorizo o uso local das fotos para esta demonstração e sei que posso apagar tudo quando quiser.</span></label><button className="primary" disabled={!consent} onClick={()=>{setProfile(p=>({...p,consentAt:new Date().toISOString()}));setStep(1)}}>Começar análise <ChevronRight/></button></section>;
 if(step===4)return <Identity profile={profile} setProfile={setProfile} setScreen={setScreen}/>;
 const position=positions[step-1],photo=profile.photos[position];
 return <section className="card photoCard"><div className="stepLine"><span>ETAPA {step} DE 3</span><i style={{width:`${step/3*100}%`}}/></div><h1>Foto de {position}.</h1><p>Corpo inteiro visível, celular reto, roupa próxima ao corpo e iluminação uniforme.</p><label className={'photoDrop '+(photo?'hasPhoto':'')}>{photo?<img src={photo} alt={`Prévia de ${position}`}/>:<><ImagePlus/><b>Adicionar foto</b><small>JPG, PNG ou imagem do celular · até 15 MB</small></>}<input type="file" accept="image/*" onChange={e=>setPhoto(position,e.target.files?.[0])}/></label>{photoError&&<p className="fieldError" role="alert">{photoError}</p>}{photo&&<button className="textButton" onClick={()=>remove(position)}><Trash2/> Remover e escolher outra</button>}<button className="primary" disabled={!photo} onClick={()=>setStep(step+1)}>{step===3?'Responder perguntas':'Próxima foto'} <ChevronRight/></button></section>
}

function Identity({profile,setProfile,setScreen}){
 const[index,setIndex]=useState(profile.answers.length<quiz.length?profile.answers.length:0);const answers=profile.answers||[];
 const choose=answer=>{const next=[...answers];next[index]=answer;setProfile(p=>({...p,answers:next}));if(index<quiz.length-1)setIndex(index+1);else{setProfile(p=>({...p,answers:next,completed:true}));setScreen('result')}};
 return <section className="card quizCard"><div className="stepLine"><span>PERGUNTA {index+1} DE {quiz.length}</span><i style={{width:`${(index+1)/quiz.length*100}%`}}/></div><span className="eyebrow">IDENTIDADE DE ESTILO</span><h1>{quiz[index].title}</h1><div className="options">{quiz[index].options.map(option=><button key={option} className={answers[index]===option?'selected':''} onClick={()=>choose(option)}><span>{option}</span><ChevronRight/></button>)}</div>{index>0&&<button className="textButton" onClick={()=>setIndex(index-1)}><ArrowLeft/> Voltar uma pergunta</button>}</section>
}

function Result({profile,setScreen}){const style=getStyleProfile(profile),answered=profile.answers?.length||0;return <><section className="resultHero"><span className="pill">SEU MAPA DE ESTILO</span><h1>{style.name}</h1><p>{style.summary}</p><div className="keywordRow">{style.keywords.map(word=><span key={word}>{word}</span>)}</div><div className="evidence"><Info/><span>Esta hipótese considera sua intenção (“{profile.answers?.[0]}”), sua dificuldade (“{profile.answers?.[1]}”) e {answered} respostas. As fotos ainda não são interpretadas por IA nesta versão.</span></div></section><section className="resultGrid"><article><span>01</span><b>Silhuetas</b><p>{style.silhouette}</p></article><article><span>02</span><b>Materiais</b><p>{style.materials}</p></article><article><span>03</span><b>Detalhes</b><p>{style.details}</p></article></section><section className="note"><Sparkles/><div><b>Uma hipótese, não uma caixa.</b><p>Não avaliamos peso, saúde, beleza ou valor pessoal. Você refina o mapa dizendo o que funcionou na vida real.</p></div></section><div className="dual"><button className="primary" onClick={()=>setScreen('guide')}>Abrir meu guia <BookOpen/></button><button className="secondary" onClick={()=>setScreen('looks')}>Montar um look</button></div></>}

function Guide({profile,setScreen}){const style=getStyleProfile(profile);const sections=[['Silhuetas',style.silhouette],['Materiais',style.materials],['Detalhes',style.details],['Para começar',`Monte três combinações com as palavras ${style.keywords.join(', ')} e registre quais fazem você se sentir melhor.`]];return <><section className="pageIntro"><span className="eyebrow">GUIA PESSOAL · {style.name.toUpperCase()}</span><h1>Um guia que começa em você.</h1><p>Recomendações iniciais conectadas às respostas da sua jornada.</p></section><section className="guideList">{sections.map(([title,text],i)=><article key={title}><span>0{i+1}</span><div><b>{title}</b><p>{text}</p></div><Heart/></article>)}</section><button className="primary" onClick={()=>setScreen('looks')}>Criar looks com meu guia <WandSparkles/></button></>}

function Looks({profile}){const[selected,setSelected]=useState(0),style=getStyleProfile(profile);return <><section className="pageIntro"><span className="eyebrow">STYLIST IA · {style.name.toUpperCase()}</span><h1>Looks pensados para sua vida.</h1><p>Escolha uma ocasião e veja uma composição alinhada às palavras {style.keywords.join(', ')}.</p></section><div className="chips">{looks.map((x,i)=><button className={selected===i?'active':''} onClick={()=>setSelected(i)} key={x.occasion}>{x.occasion}</button>)}</div><section className={'lookBoard '+looks[selected].tone}><div className="outfit"><span className="garment jacket"/><span className="garment topPiece"/><span className="garment pants"/></div><span className="pill">{looks[selected].occasion.toUpperCase()}</span><h2>{looks[selected].name}</h2><div className="pieceList">{looks[selected].pieces.map(x=><span key={x}><Check/> {x}</span>)}</div></section><button className="secondary full" onClick={()=>setSelected(value=>(value+1)%looks.length)}><RefreshCw/> Gerar outra combinação</button></>}

function Colors(){return <><section className="pageIntro"><span className="eyebrow">CORES & BELEZA</span><h1>Uma paleta para começar.</h1><p>Na versão completa, luz natural e perguntas de contraste refinam esta hipótese.</p></section><section className="paletteCard"><div className="swatches">{['#6d2437','#b66362','#dca28f','#edc9ae','#58634b','#1d3d42'].map(c=><i style={{background:c}} key={c}/>)}</div><h2>Profunda e suavemente quente</h2><p>Experimente vinho, rosa queimado, terracota, creme, oliva e petróleo.</p></section><section className="beautyTips"><article><b>Cabelo</b><p>Contraste médio e reflexos quentes próximos ao rosto.</p></article><article><b>Maquiagem</b><p>Blush queimado, boca rosada e definição suave.</p></article></section></>}

function Radar({profile}){const[liked,setLiked]=useState([]),style=getStyleProfile(profile);return <><section className="pageIntro"><span className="eyebrow">RADAR DE COMPRAS</span><h1>Peças que conversam com seu guia.</h1><p>Busca demonstrativa priorizando adequação ao seu estilo; preço e estoque devem ser confirmados na loja.</p></section><div className="commercialNote"><Info/> Demonstração comercial. Ofertas patrocinadas e links de afiliado serão identificados individualmente.</div><div className="searchBar"><Search/><span>{style.name} · até R$ 200</span></div><section className="productGrid">{products.map((p,i)=><article key={p.name}><div className={'productArt '+p.tone}><ShoppingBag/></div><button aria-label={`${liked.includes(i)?'Remover':'Adicionar'} ${p.name} dos favoritos`} className={liked.includes(i)?'liked':''} onClick={()=>setLiked(x=>x.includes(i)?x.filter(v=>v!==i):[...x,i])}><Heart/></button><small>EXEMPLO · NÃO PATROCINADO</small><b>{p.name}</b><strong>{p.price}</strong><span>{p.delivery}</span></article>)}</section></>}

function Professionals(){const[open,setOpen]=useState(null);return <><section className="pageIntro"><span className="eyebrow">PROFISSIONAIS</span><h1>Ajuda humana quando você quiser.</h1><p>Perfis fictícios para demonstrar o futuro marketplace.</p></section><div className="commercialNote"><Info/> Perfis de demonstração, não anúncios nem profissionais verificados.</div><div className="searchBar"><MapPin/><span>Brasília e atendimento online</span></div><section className="proList">{professionals.map((p,i)=><article key={p.name}><div className="proAvatar">{p.name[0]}</div><div><small>{p.role}</small><b>{p.name}</b><span><MapPin/> {p.place}</span><em>{p.tag}</em>{open===i&&<p className="profileDetail">Perfil demonstrativo. Agenda e contato estarão disponíveis após verificação profissional.</p>}</div><strong><Star/> {p.rating}</strong><button onClick={()=>setOpen(open===i?null:i)}>{open===i?'Fechar perfil':'Ver perfil'}</button></article>)}</section></>}

function PublicLanding({onStart}){return <main className="publicSite"><nav className="publicNav"><span className="logo">STYLIST <i>AI</i></span><button onClick={onStart}>Entrar</button></nav><section className="publicHero"><div><span className="eyebrow">CONSULTORIA DE ESTILO · BETA</span><h1>Seu estilo já existe.<br/>Vamos encontrá-lo.</h1><p>Descubra suas linhas, entenda suas preferências e transforme tudo em escolhas mais seguras — com tecnologia e apoio humano quando quiser.</p><div className="heroActions"><button className="primary" onClick={onStart}>Começar minha jornada <ChevronRight/></button><a href="#como-funciona">Conhecer as ferramentas</a></div><small>Beta gratuita para testadoras · seus dados ficam na sua conta</small></div><div className="heroPreview"><span>SEU MAPA DE ESTILO</span><h2>Elegante essencial</h2><p>Linhas limpas, intenção e escolhas que conversam com sua vida.</p><div><i>refinada</i><i>segura</i><i>atemporal</i></div></div></section><section className="publicSection" id="como-funciona"><span className="eyebrow">SUA JORNADA</span><h2>Todas as ferramentas em um só lugar.</h2><p>Você começa pelo diagnóstico e constrói um perfil que acompanha suas próximas escolhas.</p><div className="publicTools">{modules.map(({title,desc,icon:Icon})=><article key={title}><Icon/><b>{title}</b><p>{desc}</p></article>)}</div></section><section className="publicBand"><div><span className="pill">COMO FUNCIONA</span><h2>Da descoberta à vida real.</h2></div><ol><li><b>01</b><span>Crie seu perfil e conte sobre sua rotina.</span></li><li><b>02</b><span>Envie fotos guiadas e responda ao questionário.</span></li><li><b>03</b><span>Receba uma hipótese explicável e seu guia.</span></li><li><b>04</b><span>Explore looks, compras e ajuda profissional.</span></li></ol></section><section className="publicShowcase"><article><WandSparkles/><span className="eyebrow">STYLIST IA</span><h3>Looks pensados para a sua vida.</h3><p>Combinações conectadas ao seu perfil, ocasião e intenção. Nesta beta, as sugestões são demonstrativas e claramente identificadas.</p></article><article><ShoppingBag/><span className="eyebrow">RADAR DE COMPRAS</span><h3>Encontre peças com mais propósito.</h3><p>Recomendações por adequação, preço e entrega. Conteúdo patrocinado será sempre identificado.</p></article><article><UserRound/><span className="eyebrow">CONSULTORIA HUMANA</span><h3>Uma especialista quando você quiser.</h3><p>Conheça a futura experiência premium de atendimento com consultora de imagem.</p></article></section><section className="publicCta"><Sparkles/><h2>Pronta para descobrir seu estilo?</h2><p>Crie sua conta gratuita e salve sua jornada com segurança.</p><button className="primary" onClick={onStart}>Criar minha conta <ChevronRight/></button></section><footer><span className="logo">STYLIST <i>AI</i></span><p>Beta de consultoria de imagem assistida por tecnologia.</p><button onClick={onStart}>Entrar na minha conta</button></footer></main>}

function Auth({onBack}){
 const[mode,setMode]=useState('signup');const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');
 const submit=async event=>{event.preventDefault();setBusy(true);setMessage('');const form=new FormData(event.currentTarget);const email=String(form.get('email')).trim(),password=String(form.get('password'));
  try{if(mode==='login'){const{error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error}else if(mode==='reset'){const{error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:location.href});if(error)throw error;setMessage('Enviamos o link de recuperação para seu e-mail.')}else{if(!form.get('terms'))throw new Error('Você precisa aceitar os Termos e o Aviso de Privacidade.');if(!form.get('photos'))throw new Error('Autorize o tratamento das fotos para realizar a análise.');const profileRow={full_name:form.get('fullName'),city_state:form.get('city'),whatsapp:form.get('whatsapp')||null,instagram:form.get('instagram')||null,address:form.get('address')||null,email_marketing:Boolean(form.get('emailMarketing')),whatsapp_marketing:Boolean(form.get('whatsappMarketing')),photo_processing_consent_at:new Date().toISOString()};const{data,error}=await supabase.auth.signUp({email,password,options:{data:profileRow}});if(error)throw error;if(data.session){const{error:profileError}=await supabase.from('profiles').upsert({user_id:data.user.id,...profileRow});if(profileError)throw profileError}else setMessage('Conta criada. Confira seu e-mail para confirmar o acesso.')}}catch(error){setMessage(error.message||'Não foi possível continuar.')}finally{setBusy(false)}};
 return <main className="app authPage"><button className="backToSite" onClick={onBack}><ArrowLeft/> Voltar ao site</button><span className="logo">STYLIST <i>AI</i></span><section className="authCard"><span className="eyebrow">BETA FECHADA</span><h1>{mode==='signup'?'Crie sua conta':mode==='login'?'Entre na sua área':'Recupere seu acesso'}</h1><p>Seus resultados ficam vinculados somente à sua conta.</p><form onSubmit={submit}>{mode==='signup'&&<><label>Nome completo *<input name="fullName" required autoComplete="name"/></label><label>Cidade/UF *<input name="city" required placeholder="Brasília/DF"/></label><label>WhatsApp <small>opcional</small><input name="whatsapp" inputMode="tel" autoComplete="tel"/></label><label>Instagram <small>opcional</small><input name="instagram"/></label><label>Endereço <small>opcional</small><input name="address" autoComplete="street-address"/></label></>}<label>E-mail *<input name="email" type="email" required autoComplete="email"/></label>{mode!=='reset'&&<label>Senha *<input name="password" type="password" minLength="8" required autoComplete={mode==='login'?'current-password':'new-password'}/><small>mínimo de 8 caracteres</small></label>}{mode==='signup'&&<div className="consentList"><label><input name="terms" type="checkbox"/><span>Aceito os Termos de Uso e o Aviso de Privacidade. *</span></label><label><input name="photos" type="checkbox"/><span>Autorizo o tratamento das fotos para realizar minha análise. *</span></label><label><input name="emailMarketing" type="checkbox"/><span>Quero receber novidades por e-mail. <small>opcional</small></span></label><label><input name="whatsappMarketing" type="checkbox"/><span>Quero receber recomendações e promoções por WhatsApp. <small>opcional</small></span></label></div>}<button className="primary" disabled={busy}>{busy?'Aguarde...':mode==='signup'?'Criar minha conta':mode==='login'?'Entrar':'Enviar link'}</button>{message&&<p className="formMessage" role="status">{message}</p>}</form><div className="authLinks">{mode!=='login'&&<button onClick={()=>setMode('login')}>Já tenho conta</button>}{mode!=='signup'&&<button onClick={()=>setMode('signup')}>Criar conta</button>}{mode==='login'&&<button onClick={()=>setMode('reset')}>Esqueci minha senha</button>}</div></section></main>
}

function Account({session,profile,setScreen,setProfile}){const items=[['Meu Perfil de Estilo',profile.completed?'Resultado disponível':'Ainda não concluído','result'],['Minhas Análises',profile.photos&&Object.keys(profile.photos).filter(x=>profile.photos[x]).length+' de 3 fotos','analysis'],['Meus Guias',profile.completed?'Guia beta liberado':'Conclua sua análise','guide'],['Stylist IA','Recomendações demonstrativas','looks'],['Favoritos',(profile.favorites?.length||0)+' itens','radar'],['Radar de Compras','Produtos demonstrativos','radar'],['Minha Consultora','Agendamento em breve','pros']];return <><section className="pageIntro"><span className="eyebrow">ÁREA DA CLIENTE</span><h1>Minha conta.</h1><p>{session?.user?.email||'Modo de demonstração local'}</p></section><section className="accountList">{items.map(([title,detail,target])=><button key={title} onClick={()=>setScreen(target)}><span><b>{title}</b><small>{detail}</small></span><ChevronRight/></button>)}</section><section className="accountActions"><button onClick={()=>setScreen('feedback')}><MessageSquare/> Avaliar esta beta</button><button onClick={()=>setScreen('account')}><Settings/> Preferências de comunicação</button><button onClick={()=>{if(confirm('Apagar fotos, respostas e resultados desta conta?'))setProfile({answers:[],photos:{},favorites:[],completed:false})}}><Trash2/> Privacidade e apagar meus dados</button>{session&&<button onClick={()=>supabase.auth.signOut()}><LogOut/> Sair</button>}</section></>}

function Feedback({session,setScreen}){const[sent,setSent]=useState(false);const[error,setError]=useState('');const submit=async event=>{event.preventDefault();const form=new FormData(event.currentTarget),answers=Object.fromEntries(form.entries());try{if(backendReady){const{error:saveError}=await supabase.from('feedback').insert({user_id:session.user.id,answers});if(saveError)throw saveError}else save('stylist_feedback',answers);setSent(true)}catch(e){setError(e.message)}};if(sent)return <section className="card feedbackThanks"><Check/><h1>Obrigada!</h1><p>Seu feedback foi salvo e vai orientar a próxima versão.</p><button className="primary" onClick={()=>setScreen('home')}>Voltar ao início</button></section>;return <section className="card feedbackForm"><span className="eyebrow">FEEDBACK DA BETA</span><h1>Conte como foi.</h1><form onSubmit={submit}>{['Foi fácil criar a conta?','Você entendeu o resultado?','O resultado pareceu útil?','Você usaria novamente?','Você pagaria por um Guia Personalizado?','Teria interesse em uma consultora humana?'].map((question,i)=><fieldset key={question}><legend>{question}</legend><label><input type="radio" name={'q'+i} value="sim" required/> Sim</label><label><input type="radio" name={'q'+i} value="mais-ou-menos"/> Mais ou menos</label><label><input type="radio" name={'q'+i} value="nao"/> Não</label></fieldset>)}<label>O que ficou confuso?<textarea name="confuso" rows="3"/></label><label>O que você mais gostou?<textarea name="melhor" rows="3"/></label><label>O que faltou?<textarea name="faltou" rows="3"/></label>{error&&<p className="fieldError">{error}</p>}<button className="primary">Enviar feedback</button></form></section>}

createRoot(document.getElementById('root')).render(<App/>);
